# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Basic Checks and Tests"
description: "Perform basic checks and tests for an NPM project"
inputs:
  node-version:
    required: true
    description: "the node version"
  working-directory:
    required: false
    description: "Working directory"
    default: "."

runs:
  using: "composite"
  steps:
    # Action level setup steps
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    # Directory level tasks
    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: npx --no-install prettier --check .
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: npm run lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: npm run test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
