# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Basic Checks and Tests"
description: "Perform basic checks and tests for a yarn project"
inputs:
  node-version:
    required: true
    description: "the node version"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    # Yarn equivalent of npm ci.
    - run: yarn install --frozen-lockfile
      shell: bash
    - run: yarn prettier --check .
      shell: bash
    - run: yarn lint
      shell: bash
    - run: yarn test
      shell: bash
