# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Basic Checks and Tests"
description: "Perform basic checks and tests for a yarn project"
inputs:
  node-version:
    required: true
    description: "the node version"
  build:
    required: false
    type: boolean
    description: "enables the build step"
    default: false
  integration-tests:
    required: false
    type: boolean
    description: "Runs Cypress tests"
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - if: ${{ inputs.integration-tests == 'true' }}
      name: "Integration tests"
      uses: cypress-io/github-action@v3
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        install: false
        record: true
        start: yarn start
        wait-on: http://localhost:8000
        wait-on-timeout: 120
        config: baseUrl=http://localhost:8000
    # Yarn equivalent of npm ci.
    - run: yarn install --frozen-lockfile
      shell: bash
    - run: yarn prettier --check .
      shell: bash
    - run: yarn lint
      shell: bash
    - if: ${{ inputs.build == 'true' }}
      run: yarn build
      shell: bash
    - run: yarn test
      shell: bash
