name: "Publish Image to Docker Hub"
description: "Build and push docker image to docker hub"
inputs:
  docker_username:
    required: true
    description: "secrets.DOCKER_USERNAME"
  docker_password:
    required: true
    description: "secrets.DOCKER_PASSWORD"
  tags:
    required: true
    description: "comma separate string of tags to push"

# Define action steps
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
