# Define action name, description, and inputs
name: "Python Black Lint"
description: "Lint python code with black"
inputs:
  working-directory:
    required: false
    description: "Working directory"
    default: "."

# Define action steps
runs:
  using: "composite"
  steps:
    # Action level setup steps
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
        architecture: x64

    # Directory level tasks
    - run: pip install black
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: black --check .
      shell: bash
      working-directory: ${{ inputs.working-directory }}
