name: CI and Release
on:
  push:
  schedule:
    # Run daily at 1:15am
    - cron: "15 1 * * *"
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yamllint

  # Check if there were any changes since the last tag if this is not a push
  # event
  changes:
    needs: [yamllint]
    runs-on: ubuntu-latest
    outputs:
      updates: ${{steps.changes.outputs.any == 'true'}}
    if: ${{ github.event_name != 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - uses: ./.github/actions/changes-since-last-tag

  # Make a release if
  # - there were changes and this is a scheduled job
  # - This is a manually trigger job, i.e. workflow_dispatch
  release:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.updates == 'true' && github.event_name == 'schedule') || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          version-bump: ${{inputs.version}}
