name: Dockerfile Lint

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        description: "path to dockerfile"
        default: "Dockerfile"

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ${{ inputs.dockerfile }}
